#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

readonly repo=shellbro/clojure
readonly tag="$(cat VERSION)-$(date +%s)"

docker pull "$repo:latest"
docker tag "$repo:latest" "$repo:$tag"
docker push "$repo:$tag"

git pull origin master
git tag "$tag"
git push origin "$tag"
