#!/bin/bash

sudo docker build --pull\
                  --build-arg=HOST_UID="$(id -u)"\
                  --build-arg=HOST_GID="$(id -g)"\
                  -t localhost:5000/shellbro/clojure:latest "$@" .
